configure script: Check that the specified PKCS#11 module is valid

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -257,6 +257,13 @@ if [ "$enable_pkcs11" = 1 ]; then
         if [ "x${pkcs11Module%opensc-pkcs11.so}" != "x$pkcs11Module" ]; then
             echo "Make sure that you have installed OpenSC!" >&2
         fi
+    elif type readelf grep > /dev/null 2> /dev/null; then
+        # Check that it's actually a PKCS#11 module
+        if ! readelf -s "$pkcs11Module" | grep -q C_Initialize; then
+            echo >&2
+            echo "ERROR: $pkcs11Module is not a PKCS#11 module" >&2
+            echo "Normally you should use the file opensc-pkcs11.so from OpenSC." >&2
+        fi
     fi
 else
     echo "    PKCS#11 smartcard support disabled"
